# Generated by Django 3.1.1 on 2020-09-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200923_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fire_date',
            field=models.DateField(default=None, null=True, verbose_name='Дата увольнения'),
        ),
    ]
